# Generated by Django 4.2.6 on 2023-11-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_alter_review_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='length',
        ),
    ]
